/*
 *
 * RestaurantsPage constants
 *
 */

export const FETCH_RESTAURANTS = 'app/MapPage/FETCH_RESTAURANTS';
export const FETCH_RESTAURANTS_SUCCESS =
  'app/MapPage/FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_ERROR = 'app/MapPage/FETCH_RESTAURANTS_ERROR';
export const FETCH_RESTAURANT = 'app/MapPage/FETCH_RESTAURANT';
export const FETCH_RESTAURANT_SUCCESS = 'app/MapPage/FETCH_RESTAURANT_SUCCESS';
export const FETCH_RESTAURANT_ERROR = 'app/MapPage/FETCH_RESTAURANT_ERROR';
